language: objective-c
install: make setup
osx_image: xcode8.3
rvm: ruby-2.3.0
script: make test
before_deploy:
  - make deploy
  - codesign --deep --force --sign "Mac Developer: linus@oleander.nu (8Z44P9V4VF)" Dist/BitBar.app
cache:
  - bundler
  - cocoapods
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  file: Dist/BitBar.zip
  on:
    branch: master
    condition: "-n $encrypted_34de277e100a_key"
