language: objective-c
xcode_sdk: macosx10.12
matrix:
  include:
    - osx_image: xcode8.2
    - osx_image: xcode8.1
    - osx_image: xcode8
    - osx_image: xcode7.3
    - osx_image: xcode6.4
before_install:
  - gem install cocoapods xcpretty --no-ri --no-rdoc
install:
  - make deps
script:
  - make ci
env:
  - TRAVIS=1