language: objective-c
install: make install_deps
osx_image: xcode8.3
rvm: ruby-2.3.0
script: make test
before_deploy: make deploy
cache:
  - bundler
  - cocoapods
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  file: Dist/BitBar.dmg
  on:
    branch: master
    condition: "-n $encrypted_34de277e100a_key"
