language: objective-c
install:
  - make rem
  - make setup
osx_image: xcode8.3
rvm: ruby-2.3.0
script:
  - fastlane test
  # - tailor --max-severity=error --config .tailor.ym
before_deploy: fastlane deploy
cache:
  - bundler
  - cocoapods
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  file: BitBar.zip
  on:
    branch: master
    condition: "-n $encrypted_34de277e100a_key"
