language: objective-c
osx_image: xcode7.3
xcode_workspace: App/BitBar.xcworkspace
xcode_scheme: BitBar
xcode_sdk: macosx10.11
before_install:
  - gem install cocoapods xcpretty --no-ri --no-rdoc
install:
  - make deps
script:
  - make ci
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
    master: true
