language: objective-c
xcode_workspace: App/BitBar.xcworkspace
xcode_scheme: BitBar
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
before_install:
  - gem install cocoapods xcpretty --no-ri --no-rdoc
install:
  - make deps
