language: objective-c
osx_image: xcode7.3
xcode_workspace: App/BitBar.xcworkspace
xcode_scheme: BitBar
xcode_sdk: macosx10.11
install:
  - make setup
script:
  - make ci
before_deploy:
  - make release version=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file: "BitBar-$TRAVIS_TAG.zip"
  on:
    repo: oleander/bitbar

