language: objective-c
install: make setup
osx_image: xcode8.3
script: make test
before_deploy: make build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  file: BitBar.zip
  on:
    repo: oleander/bitbar
    branch: master