language: objective-c
install: make setup
osx_image: xcode8.1
script: make ci
before_deploy: make release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  file: BitBar-beta.zip
  on:
    repo: oleander/bitbar
    branch: master