language: objective-c
osx_image: xcode8
xcode_workspace: App/BitBar.xcworkspace
xcode_scheme: BitBar
xcode_sdk: macosx10.11
install:
- make setup
script:
- make ci
before_deploy:
- make release version=$TRAVIS_TAG
deploy:
  provider: releases
  file: BitBar-$TRAVIS_TAG.zip
  on:
    repo: oleander/bitbar
  api-key:
    secure: Z8usWcRUzNAiE0fWJs02s0FIIHtVPnB78E3G45Yko8bxhTqBCA5wNZhk1MtEzfgivNI5NONYizgqlG5xFF77FGVBoNx8hU0IBGNxNC0apNeaOSmt7tSLcHmcOkRZAYoAEGJT8rpJHskoHILRTb4unMHMKyrulQ4tBcH8Zc8kHjHlPUdqCTwg196NFEZeCen5sWfEOWPxGQl2sIx9e2EcWn5ozo+/47yMXePMRqSIZQXP+9TKwUsJDSgVgLrma5yZ8ORyK0wFe28s8iIhVxb0bGPNPSksjW9azSKOA3X/qKs89Eh0TlFz7OqtyqHFQbk60uL3Vop8r2iZuK4wmNw3Ck8QHbuZQQ0oQobUE7yO2ISMMxy5IGNDeoQflptnIgpQXZg9BgiRygxDjKKckF9Itolf2fPHLnANz6oPOxGyMaPw3A/6MD0aAKNhAOCA1JeQM6rHmLA7ncyqdCRnb55QHND2vsVZGaRbev9ek7BsjPl9oHRR+bJLiNK2KkGNLbrFT2mrZ435CX1engvjERt6cQ0MNyji405s2YqMyUI+oPD3Bpb0g2XWfeQR9SFz6+eNQ2Pb6q1JZ8FrmIhMxNtYHuisSYZO6fi+C4p6yaCgY7HLtutW3Pn23t9HVdEpGRC4LipQdR0JAwT23jweJyZ1U1aC0GUHbg9RApr7RnJLFVo=
before_install:
- openssl aes-256-cbc -K $encrypted_34de277e100a_key -iv $encrypted_34de277e100a_iv
  -in key.p12.enc -out key.p12 -d
