fastlane_version "2.26.1"
default_platform :mac

platform :mac do
  before_all do
    ensure_git_status_clean
    cocoapods repo_update: true
    enable_automatic_code_signing
    # update_project_codesigning(
    #   path: "BitBar.xcodeproj",
    #   use_automatic_signing: true,
    #   team_id: "8Z44P9V4VF"
    # )
  end

  desc "Runs all the tests"
  lane :test do
    scan scheme: "BitBar", clean: true
  end

  lane :import_keys do
    # security create-keychain -p travis $(KEYCHAIN)
    # # security set-key-partition-list -S apple-tool:,apple: -s -k travis $(KEYCHAIN)
    # security default-keychain -s $(KEYCHAIN)
    # security unlock-keychain -p travis $(KEYCHAIN)
    # security set-keychain-settings -t 3600 -u $(KEYCHAIN)
    key = ENV["encrypted_34de277e100a_key"]
    iv = ENV["encrypted_34de277e100a_iv"]
    sh "cd .. && openssl aes-256-cbc -K #{key} -iv #{iv} -in Resources/bitbar.p12.enc -out bitbar.p12 -d"
    create_keychain(name: "travis", password: "travis",
      default_keychain: true, unlock: true, timeout: 3600, add_to_search_list: true)
    #  import_certificate(certificate_path: "Resources/bitbar.cer",
    #   keychain_name: "travis")
    #  import_certificate(certificate_path: "bitbar.p12",
    #   certificate_password: ENV["CERTPWD"], keychain_name: "travis")
      sh "cd .. && security set-key-partition-list -S apple-tool:,apple: -s -k travis travis"
      sh "cd .. && security import bitbar.p12 -A -k travis -P '#{ENV["CERTPWD"]}' -T /usr/bin/codesign"
      sh "cd .. && security import Resources/bitbar.cer -A -k travis -T /usr/bin/codesign"

  end

  desc "Deploy a new version to the App Store"
  lane :build do
    gym
    zip path: "BitBar.app"
    # sh "cd .. && ditto -c -k --sequesterRsrc --keepParent BitBar.app BitBar.zip"
  end

  # TODO
  # increment_build_number / increment_version_number
  # add_git_tag
  # ensure_git_branch
  # push_git_tags

  lane :lint do
    swiftlint(mode: :lint)
  end

  lane :fix do
    swiftlint mode: :autocorrect
  end
end
