fastlane_version "2.26.1"
default_platform :mac

platform :mac do
  before_all do
    cocoapods repo_update: true
    update_project_codesigning(
      path: "BitBar.xcodeproj",
      use_automatic_signing: false,
      team_id: "8Z44P9V4VF"
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan scheme: "BitBar", clean: true
  end

  # lane :key do
  #   create_keychain(
  #      name: "travis",
  #      password: ENV["CERTPWD"],
  #      default_keychain: true,
  #      unlock: true,
  #      timeout: 3600,
  #      add_to_search_list: true
  #    )
  #    match(
  #      type: "adhoc",
  #      keychain_name: "travis",
  #      keychain_password: ENV["CERTPWD"],
  #      readonly: true
  #    )
  # end

  # desc "Submit a new Beta Build to Apple TestFlight"
  # desc "This will also make sure the profile is up to date"
  # lane :beta do
  #   gym scheme: "BitBar"
  #   pilot
  # end

  desc "Deploy a new version to the App Store"
  lane :build do
    gym(
      workspace: "BitBar.xcworkspace",
      scheme: "BitBar",
      silent: true,
      clean: true
    )
  end
  # lane :release do
  #   gym scheme: "BitBar"
  #   deliver force: true
  # end
  # lane :build do
  #   gym scheme: "BitBar"
  #   deliver force: true
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
